name: belly_kitchen
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.5+1
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  google_fonts: ^3.0.1
  tcard: ^1.3.5
  flutter_svg: ^1.1.6
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.1.0
  adaptive_dialog: ^1.6.3
  flutter_staggered_grid_view: ^0.6.2
  icons_launcher: ^2.0.5
  supabase_flutter: ^1.1.0
  json_annotation: ^4.7.0
  dio: ^4.0.6
  dotenv: ^4.0.1
  url_launcher: ^6.1.6
  scroll_to_index: ^1.0.6
  photo_view: ^0.10.3
  cached_network_image: ^3.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  freezed: ^2.2.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - google_fonts/
    - assets/icon.jpeg

icons_launcher:
  image_path: 'assets/icon.jpeg'
  platforms:
    android:
      enable: true
    ios:
      enable: true